<?php

namespace Trexz\Services\Helpers;

use Illuminate\Support\Arr;
use Illuminate\Filesystem\FilesystemManager;
use Illuminate\Contracts\Filesystem\Filesystem;
use Trexz\Exceptions\ManifestDoesNotExistException;

class AssetHashService
{
    /**
     * Location of the manifest file generated by gulp.
     */
    public const MANIFEST_PATH = './build/manifest.json';

    private Filesystem $filesystem;

    protected static mixed $manifest = null;

    /**
     * AssetHashService constructor.
     */
    public function __construct(FilesystemManager $filesystem)
    {
        $this->filesystem = $filesystem->createLocalDriver(['root' => public_path()]);
    }

    /**
     * Modify a URL to append the asset hash.
     */
    public function url(string $resource): string
    {
        $data = Arr::get($this->manifest(), $resource);
        
        if (!$data) {
            return $resource;
        }
        
        $file = Arr::get($data, 'file') ?? $resource;
        // Prepend 'build/' to the path since Vite builds to public/build/
        return '/build/' . ltrim($file, '/');
    }

    /**
     * Return the data integrity hash for a resource.
     */
    public function integrity(string $resource): string
    {
        $data = Arr::get($this->manifest(), $resource);
        return Arr::get($data, 'integrity') ?? '';
    }

    /**
     * Return a built CSS import using the provided URL.
     */
    public function css(string $resource): string
    {
        $attributes = [
            'href' => $this->url($resource),
            'rel' => 'stylesheet preload',
            'as' => 'style',
            'crossorigin' => 'anonymous',
            'referrerpolicy' => 'no-referrer',
        ];

        if (config('trexz.assets.use_hash')) {
            $attributes['integrity'] = $this->integrity($resource);
        }

        $output = '<link';
        foreach ($attributes as $key => $value) {
            $output .= " $key=\"$value\"";
        }

        return $output . '>';
    }

    /**
     * Return a built JS import using the provided URL.
     */
    public function js(string $resource): string
    {
        $manifest = $this->manifest();
        $data = Arr::get($manifest, $resource);
        $output = '';
        
        // Load CSS files first if they exist for this entry point
        if ($data && isset($data['css'])) {
            foreach ($data['css'] as $cssFile) {
                $output .= '<link rel="stylesheet" href="/build/' . ltrim($cssFile, '/') . '" crossorigin="anonymous">' . "\n";
            }
        }
        
        $attributes = [
            'type' => 'module',
            'src' => $this->url($resource),
            'crossorigin' => 'anonymous',
        ];

        if (config('trexz.assets.use_hash')) {
            $attributes['integrity'] = $this->integrity($resource);
        }

        $output .= '<script';
        foreach ($attributes as $key => $value) {
            $output .= " $key=\"$value\"";
        }

        return $output . '></script>';
    }

    /**
     * Get the asset manifest and store it in the cache for quicker lookups.
     */
    protected function manifest(): array
    {
        if (static::$manifest === null) {
            self::$manifest = json_decode(
                $this->filesystem->get(self::MANIFEST_PATH),
                true
            );
        }

        $manifest = static::$manifest;
        if ($manifest === null) {
            throw new ManifestDoesNotExistException();
        }

        return $manifest;
    }
}
